####################################
### Final Exam Practice Problems ###
####################################

### Module 1 Code Practice ###

### Section 3.2 - Assignments
(x <- 10)

(y <- "Hello")

(TRUE -> z)

#### 3.3 - Data Types

(x <- 7)

(y <- x/2)

mode(x)
typeof(x)

mode(y)
typeof(y)

# Changing values from double to integer (ex: 3.5(double) to 3(integer))
(x <- as.integer(7))

(y <- as.integer(x/2))

mode(x)
typeof(x)

mode(y)
typeof(y)

# Comparing variables (logical expression)
a <- 10
b <- 20

(x <- a >= b)
(y <- (a > 5) & (b < 25))
# Both these variables are logical / comparing variables
mode(x)
typeof(x)

mode(y)
typeof(y)

# Character variables aka "strings"
(x <- "Hello")
(y <- as.character(123))

mode(x)
typeof(x)

mode(y)
typeof(y)

(x <- "Hello")
(y <- 123)
# paste function to include variables into text string
paste(x, y)

paste(x, y, "Testing", sep = ",")

(z <- sprintf("You want to say %s on %d", x, y))

nchar(z)
# Substring the variable
substr(z, start = 5, stop = 21)
# Substatute the variable with different
sub("Hello", "Bye", z)

# Complex variables
(x <- 2 + 3i)

(y <- 3 - 1i)

mode(x)
typeof(x)

x + y

x * y

#### 3.4 - Data Type Conversions


x <- TRUE
y <- FALSE

as.numeric(x)
as.numeric(y)

as.character(x)
as.character(y)
#
x <- 1
y <- 0
z <- 20

as.logical(x)
as.logical(y)
as.logical(z)

as.character(x)
as.character(y)
as.character(z)
#
x <- "TRUE"
y <- "FALSE"
z <- "20"

as.logical(x)
as.logical(y)
as.logical(z)

as.numeric(x)
as.numeric(y)
as.numeric(z)

#### 3.6 - Vectors

# Creating vectors

(ages <- c(20, 22, 23, 23, 26))


mode(ages)
typeof(ages)

(sizes <- c(12.6, 8.4))

mode(sizes)
typeof(sizes)

(x <- as.integer(sizes))
mode(x)
typeof(x)

(first.names <- c("Alice", "Bob", "Charlie"))

mode(first.names)
typeof(first.names)

(voted <- c(TRUE, FALSE, TRUE, TRUE))

mode(voted)
typeof(voted)

(x <- as.numeric(voted))

as.logical(x)



### Combining vectors ###

c(ages, sizes)

(x <- c(ages, first.names))

ages

length(ages)
sum(ages)
summary(ages)

ages/2

2 * ages

ages
ages < 25
ages >= 23

#
c(0, ages, 100)

c(ages, 2*ages)
#
x <- c(10, 20, 30, 40)
y <- c(2, 4)

x*y

x+y
#

first.names
ages
paste(first.names, ages)
paste(first.names, ages, sep=",")

#### 3.7 - Indexing

(ages <- c(21,22,23,24,25,26,27))

ages[3]
ages[1:3]
ages[c(1,5)]
ages[c(1, length(ages))]

ages
ages %% 2

ages %% 2 == 0
ages[ages %% 2 == 0]

ages %% 2 == 1
ages[ages %% 2 == 1]

ages[ages >= 24 & ages <= 26]

#### 3.8 - Sequences

seq(0, 5)

seq(from = 0, to = 5)

seq(2, 10, by = 2)

seq(from = 2, to = 10, by = 2)

seq(2, by = 2, length = 5)

seq(10, 2)

seq(from = 10, to = 2, by = -2)

seq(from = 10, by = -2, length = 5)


seq(1, 2, by = 0.25)

seq(from = 1.5, to = 4.5, by = 0.5)

rep(x, 3)

rep(x, times = 3)

rep(x, each = 3)

rep(x, times = 2, each = 3)

#### 3.10 - Named vectors

ages <- c(20, 22, 23, 23, 26)

names(ages) <- c("Alice", "Bob", 
    "Charlie", "Dave", "Ed")
    
names(ages)[2] <- "Robert"

ages

#### 3.11 - Scalar as Vector

x <- 10
x
is.vector(x)
length(x)

10 == c(10)

##
letters
paste(letters, 1:26)
paste(letters, 1:length(letters), sep = " is ")

letters[-26]
letters[-1]

paste(letters[-26], letters[-1], sep = " is before " )

#### 3.12 - Matrices

# By row
data <- c(80, 75, 85, 82, 
          90, 88, 92, 95,
          81, 78, 84, 87)

data

scores <- matrix(data,
  nrow = 3, ncol = 4,
  byrow = TRUE)

scores

# By column
data <- c(80, 90, 81, 
          75, 88, 78,
          85, 92, 84,
          82, 95, 87)

scores[c(2,3), ]

scores[ , c(1,3)] 

scores[c(2,3), c(1,3)]

#### 3.13 - Named Matrices

dimnames(scores) <- list(
   c("Alice", "Bob", "Charlie"),
   c("Quiz1", "Quiz2", "Quiz3", "Quiz4"))
   
scores

scores["Alice", "Quiz2"]

scores["Alice", ]

scores[ ,"Quiz1"]

scores[ , c("Quiz1", "Quiz3")] 

scores[c("Alice", "Charlie"), ]

scores[c("Alice", "Charlie"), 
       c("Quiz1", "Quiz3")]

rownames(scores)

colnames(scores)

is.matrix(scores)

dim(scores)

nrow(scores)

ncol(scores)

scores
as.vector(scores)

# 3.14. Modifying Matrix Entries

scores[1, 1] <- 100
scores

scores[1, ] <- 90
scores

scores["Alice", ] <- c(91, 92, 93, 94)
scores

scores["Alice", ] <- c(80, 90)
scores

scores[,] <- 100
scores

#### 3.15 - Data Frames

athlete.names   <- c("Mayweather", "Ronaldo", "James", "Messi", "Bryant")
athlete.sport   <- c("Boxing", "Soccer", "Basketball", "Soccer", "Basketball")
athlete.salary  <- c(105, 52, 19.3, 41.7, 30.5)
athlete.endorsements <- c(0, 28, 53, 23, 31)

(athlete.info <- data.frame(
  Names = athlete.names, 
  Salary = athlete.salary,
  Endorsements =  athlete.endorsements, 
  Sport = athlete.sport)
)

colnames(athlete.info)
rownames(athlete.info)

dim(athlete.info) 

nrow(athlete.info) 

ncol(athlete.info)

#### 3.16 - Accessing Data Frame Data

athlete.info[[2]]

athlete.info[["Salary"]]

athlete.info$Sport

athlete.info[ ,2]

athlete.info[ ,"Salary"]

summary(athlete.info$Sport)

summary(athlete.info$Salary)

athlete.info[3, 2]
athlete.info[3,"Salary"]
athlete.info[athlete.info$Name == "James","Salary"]

#### 3.20 - Subset of a Data Frame

subset(athlete.info, Sport == "Soccer")

subset(athlete.info, 
       Sport == "Soccer" & Salary <= 50 & Endorsements <= 28)

subset(athlete.info, Sport == "Soccer", 
       select = c(Name, Salary))
       
####  3.21 - Modifying a Data Frame

data.orig <- athlete.info

athlete.info$Salary <- c(10, 20, 30, 40, 50)

athlete.info["First", "Endorsements"] <- 100

data.orig

athlete.info
athlete.info[1,2] <- 0
athlete.info

athlete.info$Pay <- 
  athlete.info$Salary + athlete.info$Endorsements
  
  
##############################
### Module 2 Code Practice ###
##############################

# Functions

mySquare <- function (x) {
return (x*x)
}

mySquare(5)

paste("Square of 5 is", mySquare(5))

# a function with two arguments

hypotenuse <- function(x, y) {
    z_squared <- (x*x + y*y)
    return(sqrt(z_squared))
}

hypotenuse(3, 4)

#### 5.3. Control Structures

my.maxmin <- function (x, y) {
  if (x < y) {
    return (c(y, x))
} else {
    return (c(x, y))
  }
}

my.maxmin(100, 200)
my.maxmin(100, 20)


## Loops - for statement

x <- c(10, 20, 30, 40, 50)

for (i in x) {
  cat("Square of ", i, " = ", i*i, "\n") ; i
}


# Squares of first n numbers

n <- 10

for (i in 1:n) {
  cat("Square of ", i, " = ", i*i, "\n"); i
}

# Squares of odd numbers up to n

n <- 10

for (i in seq(1,n, by = 2)) {
  cat("Square of ", i, " = ", i*i, "\n"); i
}

# Loops - while statement

# Sum of first n numbers

n <- 15
sum <- 0
i <- 1

while (i <= n) {
  sum <- sum + i
  i <- i+1
}
cat("Sum of first ", n, " numbers = ", sum)

# Sum of first x numbers not to exceed given limit
limit <- 550
sum <- 0
i <- 0

while (TRUE) {
  i <- i+1
  sum <- sum + i
  if (sum >= limit) break
}

if (sum > limit) {
  sum <- sum - i
  i <- i-1
}

cat("Sum of first ", i, " numbers = ", sum)

#### 2.2. Probability - Sample Space


library(prob)

# Quiz Question 4 on Probability:
# When two six-faced dice are rolled, what is the probability that the sum of the rolls is less than or equal to 11?
outcomes <- rolldie(2, makespace = T)
outcomes
prob(outcomes, X1 + X2 <= 11)

# Quiz Question 5 on Probability:
# When two six-faced dice are rolled, what is the probability that the sum of the rolls is at least 6?
outcomes <- rolldie(2, makespace = T)
outcomes
prob(outcomes, X1 + X2 >=6)


# Quiz Question 6 on Probability:
# When three six-faced dice are rolled, what is the probability that each of them are greater than 2?
outcomes <- rolldie(3, makespace = T)
outcomes
prob(outcomes, X1 > 2 & X2 >2 & X3 >2)

#### Negative Binomial Dist ###

# Suppose a student has 60% chance of scoring a perfect score in an exam with randomly selected questions. The student has to repeatedly take the exam until they achieve three perfect scores.

# a) Compute and plot the probability distribution for scoring the three perfect scores (both the PMF and CDF). The student will only go for a maximum of 10 failures before giving up.

n = 3

p = 0.6

(pmf <- dnbinom(0:10, size = n, prob = p))

plot(0:10, pmf, type = "h", xlab = "x", ylab = "PMF")
abline(h=0)

(cdf <- cumsum(pmf))

plot(0:10, cdf, type = "h", xlab = "x", ylab = "CDF")
abline(h=0)

#### 2.15. Negative Binomial Distribution

r <- 3  # Number of successes (fixed)
p <- 0.5

# P(X = 5)   five failures before getting 3 successes
# 2 successes in the first 7 attempts, 8th is success

choose(7, 2) * (p**r) * ((1-p)**5) 

dnbinom(5, size = r, prob = p)

# Distribution of probabilities

pmf <- dnbinom(0:20, size = r, prob = p)
pmf

#Plot PMF
plot(0:20,pmf,type="h",
  xlab="x",ylab="PMF", ylim = c(0, 0.2))
abline(h=0, col="red")

# Expected value   r * (1-p)/p

sum(0:20 * pmf)



# P(X <= 5)   at most 5 failures

sum(dnbinom(0:5, size = r, prob = p))

pnbinom(5, size = r, prob = p)

# P(X > 5)   at least 6 failures

1 - pnbinom(5, size = r, prob = p)

#or

pnbinom(5, size = r, prob = p, lower.tail = FALSE)


cdf <- c(0, cumsum(pmf))
cdf

cdfplot <- stepfun(0:10, cdf)
plot(cdfplot, verticals = FALSE, pch = 16,
  main = "", xlab = "x", ylab = "CDF")

# random numbers from the distribution

rnbinom(20, size = r, prob = p)

x <- rnbinom(1000, size = r, prob = p)
plot(table(x))















