# Lecture #2 Notes
# 9/14/22

Prob <- prob::prob #assign prob to upper-case

###V

tosscoin(1)

tosscoin(1, makespace=TRUE)

tosscoin(2)

tosscoin(2, makespace=TRUE)

tosscoin(3)

tosscoin(3, makespace=TRUE)

(S <- tosscoin(3, makespace=TRUE))

subset(S, toss1 == "H" & toss3 == "H")
Prob(S, toss1 == "H" & toss3 == "H")

###V

rolldie(1)

rolldie(2)

rolldie(1, nsides = 4)

(S <- rolldie(2, makespace = TRUE))

subset(S, X1 + X2 >=10)
Prob(S, X1 + X2 >=10)

# Conditional Probability
## Event A - the two rolls are the same
(A <- subset(S, X1 == X2))
Prob(A)

(B <- subset(S, X1 + X2 >=9))
Prob(B)

Prob(B, given=A)

###V

urnsamples(1:5, size = 3)

urnsamples(1:5, size = 3, replace = FALSE, ordered = TRUE)

# Conditional always has GIVEN in the statement. Like whats the probability of X given Y.

# Example: In an university, 60% are undergraduate students, 35% are graduate students, and 5% are postdocs. 55% of undergraduates are female, 15% of graduate students are female, and 10% of postdocs are female. What is the probability that a randomly selected student is female?

# Event B = Selected student is a female
# Event A1 = Selected student is an undergraduate
# Event A2 = Selected student is a graduate Event A3 = Selected student is a postdoc

# A1, A2, and A3 are mutually exclusive and exhaustive
# P(B) = P(A1 and B) + P(A2 and B) + P(A3 and B)
# P(B) = P(B|A1)*P(A1) + P(B|A2)*P(A2) + P(B|A3)*P(A3) = 0.55*0.60 + 0.15*0.35 + 0.10*0.05
# = 0.3875
# With a probability of 0.3875, a randomly selected student is a female



# Part 1) Probability
# Use the Bayes theorem to calculate the following probabilities. Show the individual steps of the Bayes theorem. You can use R for the calculations. Use the Word/PDF document for this part. 
# Suppose that in a particular state, among 10000 people surveyed, 4250 people are in the age group 18-34 years, 2850 people are in the age group 35-49 years, 1640 people are in the age group 50-64 years, and the remaining are 65 years & over. 
# Out of those in the age group 18-34 years, 1062 people had a BMI of above 30. Of those in the age group 35-49 years, 1710 people had a BMI of above 30. Among those in the 50-64 years range, 656 people had a BMI of above 30. In the last age group, 189 people had a BMI of above 30. 

# a) What is the probability that a randomly selected person in this survey will have a BMI of above 30? 






