# CS544 Module 1 Review (Practice)

# Q1

## a) Assign the above data as a vector in the same order to the variable scores. Use this variable scores for the remaining problems.

(scores <- c(58, 46, 50, 90, 42, 52, 62, 44, 96, 92, 54, 82))

## b) Using the length function, compute how many students took the exam? Store the expression in the variable n. Use this variable for the remaining problems where required.

(n <- length(scores))

## c) Using indexing, write the expression for accessing the first two items. Store the expression in the variable first_and_second.

(first_and_second <- scores[1:2])

## d) Using indexing, write the expression for accessing the first and last items. Store the expression in the variable first_and_last.

(first_and_last <- scores[c(1, length(scores))])


(first_and_last <- scores[c(1, length(scores))])

## e) Using indexing, write the expression for accessing the middle two items. Store the expression in the variable middle_two.

(middle_two <- scores[c(length(scores)/2, length(scores)/2+1)])

(middle_two <- scores[c(length(scores)/2, length(scores)/2+1)])

# Q2

## a) Use median(scores) to compute the median of the data. Store the expression in the variable median_score.
(median_score <- median(scores))

## b) Using comparison operators, write the R expression for scores less than or equal to the median of the data. Store the expression in the variable below_median.

(below_median <- scores <= median_score)

## c) Using comparison operators, write the R expression for scores greater than the median of the data. Store the expression in the variable above_median.

(above_median <- scores > median_score)

## d) Using the sum function, write the R expression for the number of scores less than or equal to the median of the data. Store the expression in the variable count_below_median.

(count_below_median <- sum(scores <= median_score))

## e) Using the sum function, write the R expression for the number of scores greater than the median of the data. Store the expression in the variable count_above_median.

(count_above_median <- sum(scores > median_score))

# Q3

## a) Using logical indexing and the results from Q2), write the R expression for all the scores that are less than or equal to the median value of the data. Store the expression in the variable scores_below_median.

(scores_below_median <- scores[c(scores <= median_score)])

## b) Similarly, write the R expression for all the scores that are greater than the median. Store the expression in the variable scores_above_median.

(even_index_values <- scores[c(scores > median_score)])

# Q4

## a) Using numeric indexing, write the R expression for the odd indexed values from the scores. Store the expression in the variable odd_index_values.

# You must use the seq() function to generate the numeric indices for the above.

(odd_index_values <- scores[seq(from = 1, by = 2, to = length(scores))])

(odd_index_values <- scores[seq(from = 1, to = length(scores), by = 2)])

## b) Similarly, write the R expression for the even indexed values from the scores. Store the expression in the variable even_index_values.

# You must use the seq() function to generate the numeric indices for the above.

(even_index_values <- scores[seq(from = 2, by = 2, to = length(scores))])

(even_index_values <- scores[seq(from = 2, to = length(scores), by = 2)])

# Q5

## a) Using the paste function with LETTERS, write the expression for the following output. Store the expression in the variable format_scores_version1.
# You can assume there are no more than 26 values.


(format_scores_version1 <- paste(LETTERS, sep='=', scores))

## b) Similarly, using the paste function with LETTERS, write the expression for the following output. Store the expression in the variable format_scores_version2.

(format_scores_version2 <- rev(paste(sort(LETTERS, decreasing=FALSE), sep="=", rev(scores))))

(format_scores_version2 <- rev(paste(sort(LETTERS, decreasing=FALSE), sep="=", rev(scores))))

(format_scores_version2 <- rev(paste(sort(LETTERS, decreasing=FALSE), sep="=", rev(scores))))

(format_scores_version2 <- rev(paste(sort(LETTERS, decreasing=FALSE), sep="=", scores)))


# Q6

## a) Create a matrix with two rows using the scores data. The first half of the values belong to the first row of the matrix. Store the expression in the variable scores_matrix.
#The code should work for any size input data.
#You can assume that there are even number of values in scores.

(scores_matrix <- matrix(scores, nrow = 2, byrow=TRUE))

(scores_matrix <- matrix(scores, nrow=2, byrow=TRUE))

## b) Write the expression for displaying the first and last columns of the above matrix. The code should work for any size matrix. Store the expression in the variable first_and_last_version1.

(first_and_last_version1 <- scores_matrix[, c(1, ncol(scores_matrix))])

(first_and_last_version1 <- scores_matrix[, c(1, ncol(scores_matrix))])

# Q7

## a) Copy scores_matrix to the variable named_matrix.
# Assign column names for the named_matrix as Student_1, Student_2,... and row names as Quiz_1, Quiz_2, ... The code should work for any size matrix, i.e., for any number of columns in the matrix and any number of rows. The code can contain multiple statements.


(named_matrix <- scores_matrix)

(size <- dim(named_matrix))

(col_names <- paste0('Student_', seq(size[2])))

(row_names <- paste0('Quiz_', seq(size[1])))

dimnames(named_matrix) <- list(row_names,col_names)
named_matrix

## b) Show the result for displaying the first and last columns of the named_matrix. The code should work for any size matrix. Store the expression in the variable first_and_last_version2.

(first_and_last_version2 <- named_matrix[, c(1, ncol(named_matrix))])

(first_and_last_version2 <- named_matrix[, c(1, ncol(named_matrix))])

(first_and_last_version2 <- named_matrix[, c(1, ncol(named_matrix))])


                  ####### QUIZ 1 CODE  #######

#Q1
data <- c(5940, 8900, 6520, 7760,
          7240, 5740, 2080, 1820,
          3140, 2940, 1660, 8740)

(scores <- matrix(data, nrow=3, byrow=TRUE))

scores

mean(scores[1,])

#Q2
iqr <- c(3170, 4490, 6440, 6450, 6700, 8260, 8680, 8840, 8950, 9750)

fivenum(iqr)
summary(iqr)

#q3
z_score <- c(10, 14, 22, 24, 52)

mean(z_score)

sd(z_score)

(z_score - mean(z_score)) / sd(z_score)


(scores <- c(175, 915, 380,
            273, 727, 856,
            807, 693, 407,
            509, 587, 741,
            832, 639, 332)
            



(scores_matrix <- matrix(scores, nrow=2, byrow = TRUE))

(named_matrix <- scores_matrix)


(size <- dim(named_matrix))


(col_names <- paste0("Student_", seq(size[2])))


(row_names <- paste0("Quiz_", seq(size[1])))


dimnames(named_matrix) <- list(row_names, col_names)
named_matrix

test <- c(727,915)

mean(test)

x <- c(48, 81, 41, 57, 32, 74, 26, 83, 43, 27)

x[9]

x <- c(685, 41, 322, 286, 84, 344, 743, 333, 312, 479)

x[-1]

x <- c(1070, 5850, 6110, 1510, 3850, 2160, 7490, 1900, 5990, 4510)

summary(x)

x[x < f[2] - 1.5 * (f[4] - f[2])]
x[x > f[4] + 1.5 * (f[4] - f[2])]

x <- c(12, 14, 4, 38, 24)

var(x)


(x <- c(638, 950, 916 ,711, 844, 781, 908, 482, 328 ,306, 477, 595, 379 ,436 ,596))

QR1 <- c(638, 711, 908, 306, 379)
QR2 <- c(950, 844, 482, 477, 436)
QR3 <- c(916, 781, 328, 595, 596)

(df <- data.frame(QR1, QR2, QR3))

df

df[5,1] + df[1,2]

x <- c(529, 253, 299, 309,
      423, 338, 554, 236,
      576, 565, 612, 433)

(matrix_x <- matrix(x, nrow=3))

QR1 <- c(175, 273, 807, 509, 832)
QR2 <- c(915, 727, 693, 587, 639)
QR3 <- c(380, 856, 407, 741, 332)

(df <- data.frame(QR1, QR2, QR3))

(df[,2])

median(df[,2])


Qr1 Qr2 Qr3
A 175 915 380
B 273 727 856
C 807 693 407
D 509 587 741
E 832 639 332



matrix_x[3,] <- 612
matrix_x

(x <- c(52, 54, 128, 132, 134))

mean(x)

(x <- c(684, 123, 149, 352,
        444, 686 ,742 ,324,
        456, 699, 291, 290))

(x_matrix <- matrix(x, nrow=3, byrow=TRUE))

x_matrix

median(x_matrix[,2])

(x <- c(1980, 2400,3240 ,3830 ,6340 ,7180 ,7790, 8080, 8950, 9110))

median(x)

(x <- c())

x <- c(1980, 7790, 7180, 3240, 6340, 2400, 9110, 8950, 8080, 3830)

median(x)

x <- c(562, 815, 134, 468,
      247, 251, 135, 461,
      731, 776, 307, 115)
      
matrix_x <- matrix(x, nrow=3, byrow=FALSE)

matrix_x

matrix_x[3,2]

x <- c(48, 81, 41, 57, 32, 74, 26, 83, 43, 27)

x[9]

x <- c(685, 41, 322, 286, 84, 344, 743, 333, 312, 479)

x[-1]

x <- c(1070, 5850, 6110, 1510, 3850, 2160, 7490, 1900, 5990, 4510)

summary(x)

x <- c(62, 58, 57, 47, 82, 97, 95, 14, 78, 35)

sum(x[4:6]) 

x <- c(12, 14, 4, 38, 24)

var(x)


