# CS544 Module 1 Assignment
## Student: David J Lotito

### Instructions ###
## The following sample data shows the scores of the students in an exam: 58, 46, 50, 90, 42, 52, 62, 44, 96, 92, 54, 82

## Do the following using R code with only a single expression for each case unless specified otherwise. The solutions should be generic and work for any length of given data. You can assume there will be an even number of values in the given data.


##### Q1 ######

#### a) Assign the above data as a vector in the same order to the variable scores. Use this variable scores for the remaining problems.

scores <- c(58, 46, 50, 90, 42, 52, 62, 44, 96, 92, 54, 82)

x <- matrix(c(25, 55, 78, 14, 65, 90, 100, 43, 8, 1), nrow=4, ncol=5) # Create matrix

row_names <- c("Dave", "Matt", "John", "Mike") # Create vector with names

col_names <- paste("Test", seq(1:5)) # Use paste function to create column names test with numbers 1 to 5 with seq() function

dimnames(x) <- list(row_names, col_names) # Create matrix with list of rows and columns
x # show results

#### b) Using the length function, compute how many students took the exam? Store the expression in the variable n. Use this variable for the remaining problems where required.

n <- length(scores)
n
#### c) Using indexing, write the expression for accessing the first two items. Store the expression in the variable first_and_second.

first_and_second <- scores[1:2]
first_and_second
#### d) Using indexing, write the expression for accessing the first and last items. Store the expression in the variable first_and_last.

first_and_last <- scores[c(1,12)]
first_and_last
#### e) Using indexing, write the expression for accessing the middle two items. Store the expression in the variable middle_two.

middle_two <- scores[6:7]
middle_two

##### Q2 ######

#### a) Use median(scores) to compute the median of the data. Store the expression in the variable median_score.

median_score <- median(scores)
median_score

#### b) Using comparison operators, write the R expression for scores less than or equal to the median of the data. Store the expression in the variable below_median.

below_median <- scores <= median_score 
below_median

#### c) Using comparison operators, write the R expression for scores greater than the median of the data. Store the expression in the variable above_median.

above_median <- scores > median_score
above_median

#### d) Using the sum function, write the R expression for the number of scores less than or equal to the median of the data. Store the expression in the variable count_below_median.

count_below_median <- sum(scores <= median_score)
count_below_median

#### e) Using the sum function, write the R expression for the number of scores greater than the median of the data. Store the expression in the variable count_above_median.

count_above_median <- sum(scores > median_score)
count_above_median

##### Q3 ######

#### a) Using logical indexing and the results from Q2), write the R expression for all the scores that are less than or equal to the median value of the data. Store the expression in the variable scores_below_median.

scores_below_median <- scores[scores <= median_score]
scores_below_median

#### b) Similarly, write the R expression for all the scores that are greater than the median. Store the expression in the variable scores_above_median.

scores_above_median <- scores[scores > median_score]
scores_above_median

##### Q4 ######

#### a) Using numeric indexing, write the R expression for the odd indexed values from the scores. Store the expression in the variable odd_index_values.

odd_index_values <-  scores[seq(from = 1, to = length(scores), by = 2)]
odd_index_values

#### b) Similarly, write the R expression for the even indexed values from the scores. Store the expression in the variable even_index_values.

even_index_values <- scores[seq(from = 2, to = length(scores), by = 2)]
even_index_values

##### Q5 ######

#### a) Using the paste function with LETTERS, write the expression for the following output. Store the expression in the variable format_scores_version1.
#You can assume there are no more than 26 values.

format_scores_version1 <- paste(LETTERS, sep='=', scores)
format_scores_version1

#### b) Similarly, using the paste function with LETTERS, write the expression for the following output. Store the expression in the variable format_scores_version2.

format_scores_version2 <- rev(paste(sort(LETTERS, decreasing=FALSE), sep="=", rev(scores)))
format_scores_version2

##### Q6 ######

#### a) Create a matrix with two rows using the scores data. The first half of the values belong to the first row of the matrix. Store the expression in the variable scores_matrix.
# The code should work for any size input data.
# You can assume that there are even number of values in scores.

scores_matrix <- matrix(scores, nrow=2, byrow = TRUE)
scores_matrix

#### b) Write the expression for displaying the first and last columns of the above matrix. The code should work for any size matrix. Store the expression in the variable first_and_last_version1.

first_and_last_version1 <- scores_matrix[, c(1,ncol(scores_matrix))]
first_and_last_version1

##### Q7 ######

#### a) Copy scores_matrix to the variable named_matrix.
# Assign column names for the named_matrix as Student_1, Student_2,... and row names as Quiz_1, Quiz_2, ... The code should work for any size matrix, i.e., for any number of columns in the matrix and any number of rows. The code can contain multiple statements.

named_matrix <- scores_matrix
named_matrix

size <- dim(named_matrix)
size

col_names <- paste0("Student_", seq(size[2]))
col_names

row_names <- paste0("Quiz_", seq(size[1]))
row_names

dimnames(named_matrix) <- list(row_names, col_names)
named_matrix

#### b) Show the result for displaying the first and last columns of the named_matrix. The code should work for any size matrix. Store the expression in the variable first_and_last_version2.

first_and_last_version2 <- named_matrix[, c(1,ncol(named_matrix))]
first_and_last_version2


