# CS544 Module 4 Assignment
## Student: David J Lotito

#####################################
### Part 1) Binomial distribution ###
#####################################

# Suppose a student has 40% chance of scoring a perfect score in an exam with randomly selected questions. Each student will be provided 5 attempts.

# a) Compute and plot the probability distribution for the number of perfect scores over the 5 attempts (both the PMF and CDF)

?pbinom()

n = 5
p = 0.40

(pmf <- dbinom(0:n, size = n, prob = p))

plot(0:n, pmf, type = "h", xlab = "x", ylab = "PMF")
abline(h=0)

(cdf <- cumsum(pmf))

plot(0:n, cdf, type = "h", xlab = "x", ylab = "CDF")
abline(h=0)

# b) What is the probability that a student will score a perfect score in exactly 2 out of the 5 attempts?

n = 5
p = 0.6

pbinom(2, size = n, prob = p, lower.tail = T)

# Explicit Formula Calculation

p = 0.4
# q = 1-P = 0.6
n = 5
x = 2

5*2 * (0.4)^2 * (0.6)^3

# c) What is the probability that a student will score a perfect score in at least 2 out of the 5 attempts?

n = 5
p = 0.4

pbinom(1, size = n, prob = p, lower.tail=F)

# d) Simulate the number of perfect scores over 5 attempts for 1000 students. Show the barplot of the frequencies of successes.

n = 5
p = 0.4

r = rbinom(1000, n, p)
hist(r)

##############################################
#### Part2) Negative Binomial distribution ###
##############################################

# Suppose a student has 60% chance of scoring a perfect score in an exam with randomly selected questions. The student has to repeatedly take the exam until they achieve three perfect scores.

# a) Compute and plot the probability distribution for scoring the three perfect scores (both the PMF and CDF). The student will only go for a maximum of 10 failures before giving up.

n = 3
p = 0.6

(pmf <- dnbinom(0:10, size = n, prob = p))

plot(0:10, pmf, type = "h", xlab = "x", ylab = "PMF")
abline(h=0)

(cdf <- cumsum(pmf))

plot(0:10, cdf, type = "h", xlab = "x", ylab = "CDF")
abline(h=0)

# b) What is the probability that the student will have the three perfect scores with exactly 4 failures?
options(digits=1)
n = 3
p = 0.6

dnbinom(4, size = n, prob = p)



# Explicit Formula Calculation
#P(x = 4):
choose(6, 2) * (p**n) * ((1-p)**4) 

# c) What is the probability that the student will have the three perfect scores with at most 4 failures?

n = 3
p = 0.6

pnbinom(4, size = n, prob = p)

# d) Simulate the number of failures to get the three perfect scores for 1000 students. Show the barplot of the frequencies of the failures.

n = 3
p = 0.6

r = rnbinom(1000, n, p)
hist(r)

###########################################
#### Part3) Hypergeometric distribution ###
###########################################

# Suppose that your professor created a pool of 60 multiple choice questions and 40 programming questions for the final exam. For each student, a random set of 20 distinct questions from the pool will be presented during the exam. The student has the opinion that the multiple-choice questions are easy to handle than the programming questions.

# a) Compute and plot the probability distribution for the number of multiple choice questions out of the 20 questions that the student will be given?
options(scipen=999)
M = 80
N = 40
K = 20
(q_a <- dhyper(0:K, m = M, n = N, k = K))

plot(0:K, q_a, type = "h", xlab = "x", ylab = "Question A")
abline(h=0)

# b) What is the probability that the student will have exactly 10 multiple choice questions out of the 20 questions in the exam?

M = 80
N = 40
K = 20

dhyper(10, m = M, n = N, k = K)

# # Explicit Formula Calculation

choose(M,10) * choose(N,10) / choose(M+N, 20)



# c) What is the probability that the student will have at least 10 multiple choice questions out of the 20 questions in the exam?

phyper(10, m = M, n = N, k = K, lower.tail = F)

# d) Simulate the number of multiple choice questions for 1000 students. Show the barplot of the frequencies of the multiple-choice questions.

(students_1k <- rhyper(1000, m = M, n = N, k = K))

hist(students_1k)

####################################
#### Part4) Poisson distribution ###
####################################

# Suppose that, on an average, students email 10 questions per day to the professor.

# a) What is the probability that the professor will have to answer exactly 8 questions per day?

dpois(8, lambda = 10)

# b) What is the probability that the professor will have to answer at most 8 questions per day?

ppois(8, lambda = 10)

# c) What is the probability that the professor will have to answer between 6 and 12 questions (inclusive)?

diff(ppois(c(5, 12), lambda = 10))

# d) Calculate and plot the PMF for the first 20 questions.

(pmf <- dpois(0:20, lambda = 10))

plot(0:20, pmf, type = "h", xlab = "x", ylab = "PMF", xlim = c(0, 22))
abline(h=0)

# e) Suppose the course runs for 50 days. Simulate the number of questions the professor gets per day over the course run. Show a barplot of the frequencies of the number of questions. Show a boxplot of the number of questions. What do you infer from the plots?

lambda = 10

course_time = 50

(number_questions = rpois(course_time,lambda))

boxplot(number_questions, horizontal = T, main = "Questions Per Day")

###################################
#### Part5) Normal distribution ###
###################################

# Suppose that visitors at a theme park spend an average of $100 on souvenirs. Assume that the money spent is normally distributed with a standard deviation of $10.

# a) Plot the PDF of this distribution covering the three standard deviations on either side of the mean.
x <- seq(60,140)

(pdf <- dnorm(x, mean = 100, sd = 10))

plot(x, pdf, type="l", col="red",xaxt="n",xlab="Spending",ylab="PDF",main="Spending on Souvenirs")
axis(side = 1, at = seq(60,140,10), 
     labels = TRUE)

# b) What are the chances that a randomly selected visitor will spend more than $120?

pnorm(120,100,10,lower.tail=F)

# c) What is the chance that a randomly selected visitor will spend between $80 and $90 (inclusive)?

pnorm(90,100,10)-pnorm(80,100,10)

# d) What are the chances of spending within one standard deviation, two standard deviations, and three standard deviations, respectively?

# 1 SD
pnorm(110,100,10)-pnorm(90,100,10)
# 2 SD
pnorm(120,100,10)-pnorm(80,100,10)
# 3 SD
pnorm(130,100,10)-pnorm(70,100,10)

# e) Between what two values will the middle 80% of the money spent will fall?

qnorm(0.10,100,10)
qnorm(0.90,100,10)

# f) If the theme park gives a free T-shirt for the top 2% of the spenders, what will be the minimum amount you have to spend to get the free T-shirt?

qnorm(0.98, 100, 10)

# g) Show a plot for 10,000 visitors using the above distribution.

plot(table(round((rnorm(10000,100,10)))),type="h",xaxt="n",xlab="Spending",ylab="Frequency",main="10,000 Visitors")
axis(side=1, at=seq(60,140,10),labels=T)



