# Module 1 Lecture Notes

# The following are student exam scores, lets get the average!
exam_mean <- mean(c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94))
print(exam_mean)

# The following are student exam scores, lets get the middle number!
exam_median <- median(c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94))
print(exam_median)

# The following are student exam scores, lets find the variance
exam_score_variance <- var(c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94))
print(exam_score_variance)

# The following are student exam scores, lets find the standard deviation!
std <- sd(c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94))
print(std)

# The following are student exam scores, lets find the five num summary
students_five_num <- fivenum(c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94))
print(students_five_num)

# Student test scores dataset
x <- c(72, 22, 85, 89, 96, 77, 69, 78, 83, 92, 94)

# Compute fivenum summary
f <- fivenum(x)

# Find Outlier: Outlier is 22 from the dataset
x[x < f[2] - 1.5 * (f[4] - f[2])]
x[x > f[4] + 1.5 * (f[4] - f[2])]

# Alternative is to get the summary - this computes all the above in one line of code
summary(x)

# Find the standarized variables of the exam scores from above ^ (x)
(x - mean(x)) / sd(x)

### DATA TYPES ###

y = 3.5
typeof(y)
mode(y)

# Create integer objects #
y_int <- as.integer(y)
print(y_int)
typeof(y_int)
mode(y_int)

y_int_2 <- as.integer(y/2)
print(y_int_2)
typeof(y_int_2)

# Return as a character
as.character(123)


# Concat strings with paste() function!

concat_1 <- "Dave"
concat_2 <- "Lotito"

paste(concat_1, concat_2, sep = "_")

# Return strings in specified format using sprintf() function!
day = "Saturday"
hour = "09:00"
sprint_f_test <- sprintf("This is a test at %s on %s", hour, day)
sprint_f_test

# Find the number of characters
nchar(day)

# Get substring of string "saturday" to just grab "day"
substr(day, start=6, stop=8)

# Substitute value in string
sub("test", "test_sub", sprint_f_test)

# For the student test scores in exam 1, use logical expressions to produce only the test scores that were 90 or above!

x[x > 90]

# For the student test scores in exam 1, use logical expressions to produce only the test scores that are multiples of 4

x[x %% 4 == 0]

# Using the ‘paste’ function, convert the set of student test scores from exam 1 into the format “Student#: score” where the # will represent the position of the score in the vector. DO NOT ASSUME THAT YOU KNOW THE NUMBER OF SCORES OR STUDENTS IN THE CLASS. Show the R commands. E.g- Student1: 72, Student2: 22, etc...

paste0("Student", 1:length(x), ": ", x) # paste0 doesn't apply the default "space" sep

# The functions as.numeric, as.character, as.logical, as.integer, and as.complex are used for converting the given data into the required type. If the data cannot be converted, the value NA is returned
test_var <- 123
test_null <- NA

as.numeric(test_var)

as.character(test_var)

as.logical(test_var)

as.integer(test_var)

# In mathematics, a complex number is an element of a number system that extends the real numbers with a specific element denoted i.
as.complex(test_var)

# Check if value is null, returns boolean TRUE/FALSE
is.na(test_null)

is.numeric(test_var)

is.character(test_var)

is.logical(test_var)

is.integer(test_var)

# In mathematics, a complex number is an element of a number system that extends the real numbers with a specific element denoted i.
is.complex(test_var)

as.logical(x)

# Convert a vector of numerics to characters
char_x <- as.character(x)
char_x

# Section 3.6 - Vectors

## Since a vector is a collection of all values of the same type, in cases where different types are used during combining, the data is coerced to a common type. The type hierarchy is shown below.

# logical < integer < double < complex < character

ages <- c(20, 22, 25, 28, 29)
sizes <- c(TRUE, FALSE, TRUE, TRUE, FALSE)

combine_vectors <- c(ages, sizes)
combine_vectors

# The length function returns the number of values in the given vector. For a numeric vector, the sum function adds all the values

length(combine_vectors)

sum(combine_vectors)

ages/2

2 * ages

# Arithmetic operations on vectors result in a new vector. If the lengths of the vectors are not equal, then the elements of the shorter vector are recycled to fill the gap.

first.names <- c("Mike", "Dave", "David", "Doreen")

paste(first.names, ages, sep=": ") # The first value of the first.names vector is recycled at the end to make it the same length as the ages vector

# Instantiate a vector of numbers from 1 to 10 inclusive
vector_test <- seq(1:10)
vector_test

# Instantiate a vector of EVEN numbers from 1 to 20 inclusive
vector_test_2 <- seq(from=2, to=20, by=2)
vector_test_2

# Section 3.7 - Indexing Vectors

ages[3] # Grab the 3rd element in the vector

ages[1:3] # Grab the 1st to the 3rd element in the vector

ages[c(1,5)] # Combine the 1st and 5th element into a new vector

is.vector(ages) # Returns TRUE if the given object is a vector.

vector_test_3 <- seq(1:20)

vector_test_3[c(3,7,10)] # return the 3rd, 7th, and 10th element of vector

vector_test_3[-length(vector_test_3)] # Return all elements except for the last element

vector_test_3[vector_test_3 %% 3 == 0] # Return all elements that are divisable by 3

# Section 3.8 - Sequences

20:25

2 * 1:5

n <- 5

1:n-1 # The sequence 1 : 5 is generated and the value 1 is subtracted from each member of the sequence

seq(from=2, to=10, length=3)

## The rep function is used to replicate the given vector. The given vector can be replicated the specified number of times if the second argument is a single number
rep_test <- c(1,5,7,100,56,42)

rep(rep_test, 3)

rep(rep_test, times=10)

### The each parameter allows each value in the vector to be repeated the specified number of times. In the following example, each element of x is repeated three times

rep(rep_test, each=10)

# Section 3.9 - Modifying Vectors

mod_vec <- 1:10

mod_vec[1] <- 1000 # Change the first element to 1000 instead of 1
mod_vec

mod_vec[c(2,5)] <- c(50,20) # Change element 2 & 5 to 50 and 20 respectively
mod_vec

mod_vec[length(mod_vec)] <- 0 # Change the last element to 0 assuming I don't know the length
mod_vec

# Section 3.10 - Named Vectors

## The names function assigns character strings as the names of the elements of the vector
names(ages) <- c("Mike", "dave", "David", "Doreen")
ages

ages["dave"] # Values of the vector can be accessed

ages[c("dave", "Mike")] # combine multiple values

names(ages)

### The contents of named vectors, like the contents of regular vectors, may be modified using the name indices or the numeric indices

names(ages)[2] <- "Derek"
names(ages)

# Section 3.12 - Matrices

data <- c(85, 15, 67, 43,
          34, 54, 23, 28,
          1, 21, 90, 100) # In this example, the vector data has 12 values. 
          # A matrix with 3 rows and 4 columns is constructed with the data interpreted row-wise

scores <- matrix(data, nrow=3, ncol=4, byrow=TRUE)
scores


scores[1,2] # The contents of the matrix can be accessed using the numerical indices

scores[1,] # Everything from first row

scores[c(4:12)] # Combine all values from row 4 to 12 in one vector

## Use the same exam scores from above to create a 2 x 5 matrix. Show the R commands for accessing the element at first row, third column. Show the R commands for accessing the fourth column

scores[1,3] # Grab first row, third column

scores[,4] # Grab all of the 4th column

# Section 3.13 - Named Matrices

dimnames(scores) <- list(c("Bob", "Dave", "Ryan"),
                        c("Quiz1", "Quiz2", "Quiz3", "Quiz4")) # The row and column dimensions may be named using the #dimnames function. The function takes a list with the first argument being the vector for the row names and the second argument being the vector for the column names.
                        
scores # SHow new matrix with column names and row(index) names

## The matrix can now be indexed using the row and column names. Specifying both the values returns the corresponding entry from the matrix. Specifying only the row name returns the entire row as a named vector. Similarly, specifying only the column name will return the corresponding column as a named vector

scores["Bob",] # Ge all of bobs quiz scores

scores[,"Quiz1"] # Get all of quiz 1 scores for all students

scores[c("Bob", "Ryan"), ] # Combine Bob and Ryans quiz scores into one matrix

### The row names and column names for a named matrix can be accessed

rownames(scores) # show all row names

colnames(scores)# show all column names

#### The is.matrix function returns TRUE if the object is a matrix. The dim function returns a vector of the dimensions of the matrix. The nrow and ncol functions return the corresponding dimension values individually

is.matrix(scores) # check if matrix

dim(scores) # check number of dimensions

nrow(scores) # check number of rows

ncol(scores) # check number of columns

##### The as.vector function converts the matrix into a vector. The data is combined column-wise.

as.vector(scores)

###### Use dimnames and some of the previously explored commands to name the columns "Test 1" - "Test 5", and the rows "Dave" and "Matt"

x <- matrix(c(25, 55, 78, 14, 65, 90, 100, 43, 8, 1), nrow=2, ncol=5) # Create matrix

row_names <- c("Dave", "Matt") # Create vector with names

col_names <- paste("Test", seq(1:5)) # Use paste function to create column names test with numbers 1 to 5 with seq() function

dimnames(x) <- list(row_names, col_names) # Create matrix with list of rows and columns
x # show results

# Section 3.14 - Modifying Matrix Entries

scores[1,1] <- 1000 # A single entry in the matrix may be modified by assigning a new value to the indexed row and column.
scores

scores[2,] <- 0 # modify the entire 2nd row to have all zeros
scores

scores["Dave",] <- c(100,100,100,100) # assign entire new vector(row) for specific person
scores

## The following scenario modifies all the entries with a single value.

scores[,] <- 99
scores

### Change Bob's 3rd quiz score to a 90. Change all of Daves's scores to 80. Show the R commands when accessing by index value, and by name

scores[1,3] <- 90

scores["Dave",] <- 18
scores

scores["Bob", "Quiz4"] <- 1
scores

scores[3, ] <- rep(80, 4)
scores

scores["Dave", 1] <- rep(12) #replace first value in col 1 with 12
scores

# Section 3.15 - Data Frames

athlete.names <- c("Conor McGregor", "Tabatha Ricci", "Francis Ngannou", "Macy Barber")

athlete.gender <- c("Male", "Female", "Male", "Female")

athlete.salary <- c("25 million", "200 thousand", "2 million", "300 thousand")

athlete.age <- c(35, 28, 30, 22)

athlete.info <- data.frame(athlete.names, athlete.gender, athlete.salary, athlete.age)

athlete.info # By default, the names of the argument objects are used as the column names for the data frame.

## Explicit names for the columns can also be specified while creating the data frame.

athlete.info <- data.frame(Name = athlete.names, Gender = athlete.gender, Salary = athlete.salary,
Age = athlete.age)

athlete.info # Show results

colnames(athlete.info) # The colnames function returns the column names for the given data frame.


# Section 3.16 - Accessing Data Frame Data

## The column data of the data frame may be accessed using the numeric index or the name of the column enclosed in [[]]. The character data is returned as a factored vector. The column data can also be accessed using the $ notation.

athlete.info[[1]] # Access first column
athlete.info[, 1]
athlete.info[, "Name"]

athlete.info$Salary # Access entire column -> Salary

summary(athlete.info$Age)

### Individual values from the data frame may be accessed in different ways as shown below.

athlete.info[athlete.info$Name == "Tabatha Ricci", "Age"]

athlete.info[Name == "Macy Barber", "Age"]

# Section 3.17 - Slicing Data Frame Columns

athlete.info[1] # The columns of the data frame may be sliced to produce new data frames.
athlete.info["Name"]

## Multiple columns may be sliced to get new data frames by specifying a vector of column indices or names.

athlete.info[c(1,4)] # Combine columns 1 & 4
athlete.info[c(1,2,3)] # Combine columns 1, 2, 3
athlete.info[c("Name", "Age")]

# Section 3.18 - Naming Data Frame Rows

rownames(athlete.info) # By default row names are named numeric based on index

rownames(athlete.info) <- c("First", "Second", "Third", "Fourth") # Create a new vector and assign it to rownames() function for the data frame.
athlete.info

# Section 3.19 - Slicing Data Frame Rows

athlete.info[3,]
athlete.info["Third",]

## Multiple rows may be sliced to get new data frames by specifying a vector of row indices or row names.

athlete.info[c(1,3), ] # Combine just the first and third columns

### Logical indexing can also be used to select the desired rows. If a vector of TRUE/FALSE values is provided for the row index, only the rows corresponding to the TRUE index values are returned

athlete.info[c(TRUE, TRUE, TRUE, FALSE, FALSE)]

athlete.info$Name == "DAVE" # Check for Name "DAVE" in Name column

athlete.info[athlete.info$Name == "Tabatha Ricci", ] # Get entire row for specifc player

athlete.info[athlete.info$Age <= 28, ] # Get all players who are aged less than or equal to 28.

# Section 3.20 - Subset of a Data Frame

subset(athlete.info, Age <= 28)
subset(athlete.info, Age <= 28 & Salary == "200 thousand")
## In the above scenarios, all the columns are included in the returned data frame. The required columns can also be selected explicitly
subset(athlete.info, Age <= 28 & Salary == "200 thousand", select = c(Name, Gender))

# Section 3.21 - Modifying a Data Frame

## A new column can be added to the data frame using a vector of explicit values or as a result of a calculation using the existing columns.

data.org <- athlete.info

athlete.info$Age_Minus_Two <- athlete.info$Age - 2
athlete.info

### The individual entries in the data frame can be modified by accessing the target position using the row and column index or the row and column name

athlete.info["First", "Salary"] <- "25M"
athlete.info

#### A column can be removed entirely from the data frame by assigning the value NULL for that column.

athlete.info$Age_Minus_Two <- NULL
athlete.info

# Section 3.22 - Factors

## Factors are variables that have a limited number of different values. Factors are usually used for categorical data. The data can be a numeric vector or a character vector. The factor function creates levels for each of the distinct values. The factors are stored internally as integer values and displayed using a corresponding set of character values.

voted <- c("yes", "no", "yes", "yes", "no")
voted

f1 <- factor(voted) # The factor function converts the data using the distinct levels present in the data
f1

levels(f1) # Shows the different values associated

### The factored data can be assigned explicit labels as shown below. The no and yes levels are mapped to the levels bad and good respectively

f2 <-factor(voted, ordered=TRUE, labels = c("bad", "good"))
f2

levels(f2)

#### In the default ordering, the levels are ordered by alphabetical order. If that is not the case, the levels argument is specified with the correct ordering for the levels.

o2 <- ordered(f2, levels = c("good", "bad"))
o2

##### Use the factor() function to show the levels of the following vector: c("High", "Medium", "Low", "Medium", "Low")

x <- c("High", "Medium", "Low", "Medium", "Low")
f <- factor(x)
f
levels(f)

###### Order the factor levels as Low < Medium < High

f_order <- ordered(f, levels = c("Low", "Medium", "High"))
f_order

# 3.23 - Lists

num.data <- c(3, 5, 7)
char.data <- c("a1", "b2", "c4", "d28")

list.data <- list("Hello", num.data, char.data, 20)
list.data

## The components of a list are accessed (sliced) using the [] notation. The index can be a single value or a vector of indices.

list.data[2]

list.data[[2]]

list.data[c(2, 4)]

### Create a list holding both Bob and Sally's test scores as individual vectors

test.scores <- list(c("bob", 99), c("sally", 56))
test.scores














