# Module 2 Lecture Notes

# Section #1 - Probability

## Compute the probability of rolling two dice and having the sum of the dice be greater than 6.

## The outcomes are {(1,6), (2,5),(2,6), (3,4),(3,5),(3,6), (4,3),(4,4),(4,5),(4,6), (5,2), (5,3),(5,4),(5,5),(5,6), (6,1),(6,2),(6,3),(6,4),(6,5),(6,6)}

                  ### So, there are 21 possible outcomes out of 36. Hence, the probability is 21/36 = 0.58
                  
## Compute the probability of rolling two dice and getting exactly one 5 in the roll.

## The outcomes are {(5,1),(5,2),(5,3),(5,4),(5,6), (1,5),(2,5),(3,5),(4,5),(6,5)}

                  ### So, there are 10 possible outcomes out of 36. Hence, the probability is 10/36 = 0.28 ###
                  
## Compute the probability that from a standard deck of cards, you will draw a J, Q, K, or a Heart on the first draw. Assume no Jokers in the deck.

## The total number of outcomes are 3 * 4 + 10 = 22 (J, Q, K from the 4 suits Clubs, Diamonds, Hearts, and Spades + {A, 2, 3, ..., 10} from the Hearts). 

                ### Hence, the probability is 22/52 = 0.42 ###
                
# Install Required Packages

install.packages("combinat")
install.packages("https://cran.r-project.org/src/contrib/Archive/prob/prob_0.9-2.tar.gz",
                   repos = NULL, dependencies = TRUE)
                   
library(prob)
Prob <- prob::prob

# Section #2 - Sample Space

## The tosscoin function sets up the sample space for the experiment of tossing the coin repeatedly. The function returns a data frame object. The columns for the data frame are named toss1, toss2, .... The sample spaces for a single toss, two tosses, and three tosses are shown below.

tosscoin(1)

tosscoin(2)

tosscoin(3)

## The rolldie function sets up the sample space for the experiment of rolling a die repeatedly. The default for the number of sides of the die is 6. The function returns a data frame object. The columns for the data frame are named X1, X2, ...

## The following shows the sample spaces for a single roll of a 6-sided die and a 4-sided die respectively. The first argument is the number of rolls.

rolldie(1)

rolldie(1, nsides=4)

## Show the R commands for the space of outcomes of tossing 4 coins, and rolling 2 six-sided dice

tosscoin(4)

rolldie(2)

# Section #3 - Sampling from an Urn

## Suppose the urn has three balls labeled 1, 2, and 3 or colored red, green and blue. The following examples show the possible outcomes for a sample size 2 when sampling is done by default, i.e., unordered and done without replacement.

urnsamples(1:3, size = 2)

urnsamples(c("r", "g", "b"), size = 2)

## With replacement, the possible unordered outcomes are shown below.

urnsamples(1:3, size = 2, replace = TRUE)

urnsamples(c("r", "g", "b"), size = 2, replace = TRUE)

## With ordering and replacement, the outcomes are shown below. For example, (2, 1) and (1, 2) are separate outcomes.

urnsamples(1:3, size = 2, replace = TRUE, ordered = TRUE)

urnsamples(c("r", "g", "b"), size = 2, replace = TRUE, ordered = TRUE)

## The last scenario shows ordered sampling without replacement.

urnsamples(1:3, size = 2, replace = FALSE, ordered = TRUE)

urnsamples(c("r", "g", "b"), size = 2, replace = FALSE, ordered = TRUE)

## Many probability problems can be simulated by drawing proverbial objects from an urn.

# Use the following vector to answer the following questions. Show all R commands seq(1:10)
(x <- seq(1:10))

# Use urnsamples() to draw 3 elements from the vector, with replacement, where the order does not matter.

urnsamples(x, size=3, replace = TRUE, ordered = FALSE)

# Draw 2 elements from the vector, without replacement, where the order does matter.

urnsamples(x, size=2, replace=FALSE, ordered=TRUE)

# Draw 5 elements, without replacement, where the order does not matter.

urnsamples(x, size=5, replace=FALSE, ordered=FALSE)

# Draw 4 elements, with replacement, where the order does matter.

urnsamples(x, size=4, replace=TRUE, ordered=TRUE)

## Which of these samples has the greatest number of possible outcomes?

# Drawing 4, ordered, with replacement, produces the largest outcome space!

# Section #4 - Counting Tools

## The nsamp function calculates the above values, which is the number of rows in a sample space created by urnsamples, without explicitly generating the probability space. For an urn with 3 distinguishable elements, the number of ways for selecting 2 elements with the possible options for replacement and ordering are shown below. The default values are FALSE for replace and ordered arguments.

# Without replacement
nsamp(n = 3, k = 2, replace = FALSE, ordered = FALSE)
# With replacement
nsamp(n = 3, k = 2, replace = TRUE, ordered = FALSE)

# With ordering
nsamp(n = 3, k = 2, replace = FALSE, ordered = TRUE)

# With ordering & replacement
nsamp(n = 3, k = 2, replace = TRUE, ordered = TRUE)

## From the previous problem, we saw instances where the sample space, or outcome space, was very large. Sometimes, we only care about the size of the space, rather than each individual element. Use the nsamp() function to illustrate the size of the sample spaces seen in the previous problem. Show all R commands.

nsamp(n=10, k=3, replace=TRUE, ordered=FALSE)

nsamp(n=10, k=2, replace=FALSE, ordered=TRUE)

nsamp(n=10, k=5, replace=FALSE, ordered=FALSE)

nsamp(n=10, k=4, replace=TRUE, ordered=TRUE)

# Section #5 - Events

## The following sample space shows all the outcomes when a coin is tossed three times. The makespace option with the value TRUE creates the probability space for the outcomes by adding the probs column to the data frame. The sample space has a total of 8 outcomes. The probability for each outcome is 1/8 = 0.125.

(S <- tosscoin(3, makespace= TRUE))

## The [] operator can be used for filtering the rows of the sample space. Different approaches for selecting the rows are shown below.

S[2:4, ]

S[seq(1,8, by = 2), ]

S[c(2,4,6,8), ]

## The subset function can be used for selecting rows based on a logical condition. The following selects all rows where the third toss is a head.

subset(S, toss3 == 'H')

## The probability that the third toss is a head is 4/8 = 0.5. The sum of the probs column will also result in the same value. Similarly, the outcomes where the first toss and the third toss are heads are selected as shown below.

subset(S, toss1 == 'H' & toss3 == 'H')

## The probability that the first toss and the third toss are heads is 2/8 = 0.25.
# The following sample space shows all outcomes when a die is rolled twice. The makespace option with the value TRUE creates the probability space for the outcomes by adding the probs column to the data frame. The number of rows of the data frame is the total number of outcomes

(S <- rolldie(2, makespace = TRUE))

## The event that the two rolls are the same is the collection of outcomes filtered as shown below.

subset(S, X1 == X2)

## The probability that the two rolls are the same is 6/36 = 0.167.
# The event that the sum of the two rolls is at least 10 is the collection of outcomes filtered as shown below.

subset(S, X1 + X2 >= 10)

## The probability that the sum of the two rolls is at least 10 is 6/36 = 0.167.
# The event that the first roll is either 5 or 6 is the collection of outcomes filtered as shown below. The %in% function tests whether the values of the first argument lie anywhere within the second argument (X1 %in% 5:6). This is more convenient than specifying X1 == 5 | X1

subset(S, X1 %in% 5:6)

## The probability that the first roll is either 5 or 6 is 12/36 = 0.33.
# The following filters only the outcomes where the first roll is either 5 or 6 and the second roll is either 1 or 3.

subset(S, X1 %in% 5:6 & X2 %in% c(1,3))

## The probability of getting 5 or 6 in the first roll and 1 or 3 in the second roll is 4/36 = 0.11. The following sample space sets up all 216 outcomes when a die is rolled three times.

(S <- rolldie(3, makespace = TRUE))
nrow(S)

## The isin(x, y) function is useful for checking whether all the values of y are in x. By default, the ordered argument is FALSE. There is only one outcome where the sequences of rolls have to be 4, 5, and 6.

subset(S, isin(S, c(4,5,6), ordered = TRUE))

## If ordering is not required, all permutations of (4, 5, 6) are possible outcomes.

subset(S, isin(S, c(4,5,6))

## The second argument can be a subset. The following filter selects two values (4 and 6) that should occur in order among the three rolls.

subset(S, isin(S, c(4,6), ordered = TRUE)

## The cards() function sets the sample space for the standard deck of cards. The default option for jokers argument is FALSE. The function returns a data frame with 52 rows. The two columns of the data frame are named rank and suit.

(S <- cards(makespace = TRUE))
nrow(S)

head(S, n = 2)

## The following subsets show the 13 cards for each suit.

subset(S, suit == "Club")

subset(S, suit == "Diamond")

subset(S, suit == "Heart")

subset(S, suit == "Spade")

## The outcomes where the rank of the selected card is 2, 3, or 4 can be filtered as shown below.

subset(S, rank %in% 2:4) ## The probability that the selected card is 2, 3, or 4 is 12/52 = 0.23.

## The outcomes where the selected card is a King or a Queen can be filtered as shown below.

subset(S, rank %in% c('K', 'Q')) # The probability that the selected card is a King or a Queen is 8/52 = 0.15

## The set operations union, intersect, and setdiff perform the union, the intersection, and the difference of the given outcomes.
## For the card deck sample space S, let the event A represent the selected card suit is a Heart and the event B represent the selected card rank is either a 10 or a Queen.

S <- cards(makespace = TRUE)
A <- subset(S, suit == "Heart")
B <- subset(S, rank %in% c(10, "Q"))

## The possible outcomes for the events A and B are shown below.

A
B

## The union of the events A and B consists of all the outcomes that are in A or B or both.

union(A, B)

## The intersection of the events A and B consists of all the outcomes that are in both A and B.

intersect(A, B)

## The difference of the events A and B consists of all the outcomes that are in A but not in B.

setdiff(A, B)

## The set difference operation is not commutative. The following shows the different results for the difference of the events B and A.

setdiff(B, A)

## The complement of an event A, written as A , is the difference between the sample space, S, and the event A. setdiff(S, A) will result in all outcomes that are either Clubs, Diamonds, or Spades.

setdiff(S, A)

# Section #6 - Setting up The Probability Space

## The following code shows an alternate approach for assigning probabilities for the experiment of rolling a die. The outcomes are generated as shown below.

(outcomes <- rolldie(1))

## Since there are 6 outcomes, 6 probability values are needed. The following shows a vector of equal values.

(p <-rep(1/6, times = 6))

## The probspace function assigns the probabilities to each of the corresponding outcomes.

probspace(outcomes, probs = p)
## The above is equivalent to the rolldie invocation with makespace argument as TRUE.
rolldie(1, makespace= TRUE)

## Suppose that the die is not fair, with some faces having a better chance than the rest. The following example shows a vector of different probabilities used to set up the sample probability space.

p <- c(0.2, 0.15, 0.15, 0.15, 0.15, 0.2)
probspace(outcomes, probs = p)

## Use probspace() to set up a probability space for rolling a loaded die, where the probability of rolling of a 3 or a 4 are 0.2, and the remaining numbers have an equal probability.

(outcomes <- seq(1:6))
(1 - 2*(0.2)) / 4
(p <- c(0.15, 0.15, 0.2, 0.2, 0.15, 0.15))
(space <- probspace(outcomes, p))

# Section #7 - The Prob Function

## The Prob function calculates the probability of the specified event. Consider the sample space from the deck of cards.

(S <- cards(makespace = TRUE))

## The probability of drawing a Queen can be determined as follows: (Let A be the event for the outcomes representing drawing a Queen.)

(A <- subset(S, rank == "Q"))

## Since there are four Queen cards, the probability is 4/52 = 0.0769.
Prob(A)

Prob(S, rank == "Q")

## Let B be the event that the card is a Heart.

(B <- subset(S, suit == "Heart"))

## Since there are 13 cards, the probability of drawing a Heart is 13/52 = 0.25.
Prob(B)

Prob(S, suit == "Heart")

## The probability of the intersection of the events A and B (Queen of Hearts) is shown below.

Prob(intersect(A, B))

## The probability of the union of the events A and B (a Queen or a Heart or both) is shown below.

Prob(union(A, B))

## Use the Prob() function and cards() function to answer the following questions. Assume no jokers in the deck.

#What is the probability of the union of the two events above?

# What is the probability of drawing a Queen or King from a deck of cards?
(deck <- cards(makespace=TRUE))

(event1 <- subset(deck, rank %in% c('Q', 'K')))
prob(event1)

# What is the probability of drawing a number between 3 and 5 inclusive that it is also a Heart?

(event2 <- subset(deck, rank %in% c(3,4,5) & suit == 'Heart'))
prob(event2)
# What is the probability of the union of the two events above?
Prob(union(event1, event2))

# Section #8 - Conditional Probability

## Consider two rolls of a six-sided die. The sample space, S = {(1, 1), (1, 2), ... , (6, 6)}. The size of the sample space is #(S) = 6 * 6 = 36.

## The sample space generated in R is shown below. The first two and the last two outcomes along with the individual probabilities are also shown.

(S <- rolldie(2, makespace= TRUE))
head(S, n = 2)

tail(S, n = 2)

## Let A denote the event where both the rolls have the same value. The possible outcomes for this event are: A = {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)}
## Hence, P(A) = 6/36 = 1/6 = 0.167
## The event A is computed in R as shown below.

(A <- subset(S, X1 == X2))
Prob(A)

## Let B be the event where the sum of the two outcomes is equal to 8. The possible outcomes for this event are: B = {(6, 2), (5, 3), (4, 4), (3, 5), (2, 6)}.
## Hence, P(B) = 5/36 = 0.139
## The event B is computed in R as shown below.

(B <- subset(S, X1 + X2 == 8))
Prob(B)

## The event A # B in this example has only one outcome {(4, 4)}. Hence, P(A # B) = 1/36.
## The conditional probabilities in this example are
## P(A!B) = P(A # B)/P(B) = (1/36)/(5/36) = 1/5 = 0.2, and P(B!A) = P(A # B)/P(A) = (1/36)/(6/36) = 1/6 = 0.167 Using R, the conditional probabilities are computed as shown below.

Prob(A, given = B)

Prob(B, given = A)

## The same could be done in R in a few steps without explicitly defining the subsets A and B, as follows:

Prob(S, X1 == X2, given = (X1 + X2 == 8))

Prob (S, X1 + X2 == 8, given = (X1 == X2))

## Section #8 (continued) - Conditional Probability Example – Coin Toss Twice

## Consider two tosses of a coin. The sample space, S = {(H, H), (H, T), (T, H), (T, T)}. The size of the sample space is #(S) = 4. The sample space generated in R is shown below. The four outcomes along with the individual probabilities are also shown.

(S <- tosscoin(2, makespace = TRUE))

## Let A be the event that a head occurs. The possible subset outcomes for this event are: A = {(H, H), (H, T), (T, H)}
## Hence, P(A) = 3/4 = 0.75
## The event A is computed in R as shown below.

(A <- subset(S, isin(S, c('H'))))

# Let B be the event that a head and a tail occurs. The possible outcomes for this event are: B = {(H, T), (T, H)}.
# Hence, P(B) = 2/4 = 0.5
# The event B is computed in R as shown below.

(B <- subset(S, isin(S, c('H', 'T'))))

# Using R, the conditional probabilities are computed as shown below.

Prob(A , given = B)

Prob(B, given = A)

## Section #8 (continued) - Conditional Probability Example - Card Deck

## Consider the standard full deck of 52 playing cards. If selecting two cards from that deck in sequence, let the events A = {first card drawn is an ace} and B = {second card drawn is an ace}.
## For the first card, there are 4 aces, hence P(A) = 4/52.
## The probability for the second card being an ace depends on whether the first card is an ace or not. If the first card is an ace, then the probability of the second card also being an ace is 3/51. However, if the first card is not an ace, then the probability of the second card being an ace is 4/51.
## For generating the sample space in R for the above problem (drawing two cards), the cards function is first used to model the deck of cards
# as shown below. The data frame has two columns, rank and suit. The first four rows are also shown.

(L <- cards())
head(L, n = 4)

## The urnsamples function can be used to sample two cards randomly from the above data frame. The function with a size of 2 returns all possible pairs of rows. The first three pairs generated by this function are shown below. The sample space for our problem is this list M.

M <- urnsamples(L, size = 2)
head(M, n = 3)

## The above set consists of C(52, 2) = 1326 pairs of cards. This can be verified in R by computing the length of the generated pairs as shown below.

length(M)

choose(52, 2)

## The probability model for the sample space is computed as shown below.
##For the event that both cards are aces, the rank of both the cards should be “A”.

S <- probspace(M)

Prob(S, all(rank == "A"))

# Similarly, the probability of both cards being Clubs is calculated as follows:

Prob(S, all(suit == "Club"))

## Section #8 (continued) - Conditional Probability - Red and Blue Balls

## Consider a box with three red balls and two blue balls inside it. For the given problem of selecting two successive balls, we are interested in finding the probability that both the balls selected will be red. Let A be the event that the first ball is red, and B be the event that the second ball is also red.

## The problem can be modeled in R as follows: (The data now consists of one dimension, the color of the balls. The data is generated using
## the rep function with the red repeated three times and the blue repeated twice.)

(L <-rep(c("red", "blue"), times = c(3,2)))

## The urnsamples function can be used to generate all outcomes for selecting two balls randomly from the above list. With a size of two, the function returns all possible pairs of rows. Also, the ordered argument is set to TRUE, as the ordering of the balls is considered. The sample space for our problem is this list M.

M <- urnsamples(L, size = 2, ordered = TRUE)

## All possible outcomes of selecting two ordered pairs out of five balls are shown above. The probability space for the data along with the first two rows is computed as shown below.

S <- probspace(M)

head(S, n = 2)

## Now, for the event that both the balls are red, all the rows with X1 == “red” & X2 == “red” satisfy the criteria. An alternative is the isrep function in the prob package. isrep(S, “red”, 2) tests each row of the sample space to determine whether the value red appears two times. The probabilities of both balls being red and both balls being blue are computed as shown below.

Prob(S, isrep(S, "red", 2))

Prob(S, isrep(S, "blue", 2))

## The probability of the first ball being red and the second ball being blue can be calculated as shown below.

Prob(S, isin(S, c("red", "blue"), ordered = TRUE))

## Consider rolling a six-sided die 3 times. Let Event A represent the case where the sum of the values of three rolls is less than 10. Let Event B represent the case where the second roll is a 3. Using the rolldie() and prob() functions and whatever other functions needed, compute the probability of A, B, and A and B (intersection). Show the R commands

(S <- rolldie(3, makespace=TRUE))

(A <- subset(S, X1 + X2 + X3 < 10))
Prob(A)

(B <- subset(S, X2 == 3))
Prob(B)

(C <- intersect(A, B))
Prob(C)

## Using the probabilities from above, compute the conditional probability of B, given A, and the conditional probability of A, given B. Show the R commands.

Prob(B, given=A)

Prob(A, given=B)

## Consider drawing from a deck of cards (no Jokers). Use the cards() and urnsamples() function to simulate drawing 2 cards without replacement. Let A be the event that you have at least one Ace, let B the event you have two cards of the same rank. Compute the probability of A, B, and A and B (intersection). Then compute the conditional probability of A, given B and the conditional probability of B, given A. Show the R commands.

(cards <- cards())

(hand <- urnsamples(cards, size=2, replace=FALSE, ordered=FALSE))

S <- probspace(hand)

A <- subset(S, 'A' %in% rank)
Prob(A)

B <- subset(S, rank[1] == rank[2])
Prob(B)

C <- intersect(A, B)

Prob(A, given = B)

Prob(B, given = A)

## Section #9 - Independent Events (Coin Toss)

## The probability of having at least one head in the five coin tosses then is

(S <- tosscoin(5, makespace=TRUE))

(B <- subset(S, isrep(S, "T", 5)))
## The probability of all tails and the probability of at least one head are
Prob(B)

1 - Prob(B)

## Section #10 - Independent Events, Repeated Experiments

## The following example shows the sample space for an unbalanced coin that is tossed three times. The coin is biased, favoring heads. Since the outcomes are independent, the probability for all three heads is: 0.216

iidspace(c('H', 'T'), ntrials = 3, probs = c(0.6, 0.4))

## When the individual probabilities are not specified, all outcomes have equal probability as shown below.

iidspace(c('H', 'T'), ntrials = 3)

## Consider rolling two fair 6-sided dice. Intuitively, we understand that the two die rolls are independent events. Let A be the event that the first roll is a 2, let B be the event that the second roll is also a 2. Show the R commands to illustrate the independence of the die rolls, specifically, show that P(A and B) == P(A) * P(B)

(S <- rolldie(2, makespace=TRUE))

(A <- subset(S, X1 == 2))

(B <- subset(S, X2 == 2))

C <- intersect(A,B)

Prob(A)
Prob(B)

Prob(A) * Prob(B)

Prob(C)

## Using the iidspace() function, simulate the rolling of 5 fair 6-sided dice. Show the R commands for the probability of all rolls being greater than 3, the first roll is a 2, and the sequence: 1, 2, 3, 4, 5

S <- iidspace(c(1, 2, 3, 4, 5, 6), ntrials=5)

prob(S, X1 > 3 & X2 > 3 & X3 > 3 & X4 > 3 & X5 > 3)

prob(S, X1 == 2)

prob(S, X1 == 1 & X2 == 2 & X3 == 3 & X4 == 4 & X5 == 5)

# Section #11 - Bayes' Rule

bayes <- function (prior, likelihood) {
  numerators <- prior * likelihood
  return (numerators / sum(numerators)) 
}

bayes <- function (prior, liklihood) {
  numerators <- prior * liklihood
  return (numerators / sum(numerators))
}

(prior <- c(0.07, 0.93))

(likelihood <- c(0.9, 0.25))

bayes(prior, likelihood)

## A survey was taken of individuals aged 22-30. 40% of the individuals surveyed received a college degree. Of the individuals who had a college degree, 90% of them had parents who also received a college degree. Of the individuals who did not receive a college degree, only 20% of them had parents who received a college degree. First, compute the prior probabilities and the likelihood probabilities. Using the bayes() function defined below, compute the probability that randomly selected parents with a college degree have a child without a college degree. Show the R commands

bayes <- function (prior, liklihood) {
  numerators <- prior * liklihood
  return (numerators / sum(numerators))
}

# Let A be the event an individual has a college degree
# P(A) = 0.4
# P(~A) = 0.6

# Let B be the event the individual has parents with a college degree
# P(B | A) = 0.9
# P(B | ~A) = 0.2

# We want to compute P(~A | B) = P(~A) * P(B | ~A) / (P(~A) * P(B | ~A) +
# P(A) / P(A) * P(B | A)
# Substitute known values: 0.6 * 0.2 / (0.6 * 0.2 + 0.4 * 0.9)

prior = c(0.4, 0.6)
likelihood = c(0.9, 0.2)
bayes(prior, likelihood)

# Section #12 - Functions and Function Arguments

inc.1 <- function (x) {
  return (x+1) 
}

inc.1(10)

inc.1(c(10,20,30))

## A function with two arguments is shown below. When the function is invoked, the parameter names can be explicitly assigned the input values. If the input values are named, then the inputs can be provided in any order.

inc.2 <- function (x, y) { 
  return (x - y)
}

inc.2(10,20)

inc.2(x = 10, y = 20)

inc.2(y = 20, x = 10)

## The following example shows the mapping of the input values when only one of the arguments is named.

inc.2(10, y = 20)

inc.2(y = 20, 10)


## The above function definitions expect two arguments to be provided when the function is invoked. If one or more inputs are missing, the function invocation throws an error. The error messages show that the arguments have no defaults, and hence expect a value to be provided.

inc.2(10)

inc.2(y = 20)


## The function arguments can be provided default values as shown below. In the following function definition, the value for x is required. The value for y is optional, the default being 100.

inc.3 <- function (x, y=100) {
  return (x + y)
}

inc.3(10)

inc.3(10, 20) #providing 20 will override the default value of 100 in the function

## The following function definition has default values for both the arguments. When the function is invoked with no arguments, the defaults are used for both the arguments. In the last case, when a new value for y is provided, it has been explicitly named.

inc.4 <- function (x = 5, y = 7) {
  return (x + y)
}

inc.4()

inc.4(100)

inc.4(60, 50)

inc.4(2,3)

inc.4(y =3)

## The following example shows a function with one required parameter and two optional parameters.

inc.5 <- function (x, y = 10, z = 100) {
  return (x - y - z)
}

inc.5(1000)

inc.5(1000, 500)

inc.5(1000, 500, 200)

## The function is invoked with different combinations as shown below.

inc.5(1000, z = 200)

inc.5(1000, z = 200, y = 500)

## Section 13 - Scope of Variables

## The following example demonstrates the scope of a single variable x. The variable x is defined in the global environment.
x <- 10

foo <- function() {
  cat("#2 In foo ", x, "\n");
  x <- 20
  cat("#3 In foo ", x, "\n");
  bar()
  cat("#6 In foo ", x, "\n");
}

bare <- function() {
  cat("#4 In bar ", x, "\n");
  x <- 30
  cat("#5 In bar ", x, "\n");
}

## The following example shows the function with two arguments. The local scope for the function includes the two function parameters (a and b) and the three variables defined locally (x, y, and z).

rm(z)

x <- 10
y <- 20

test.1 <- function(a,b) {
  x <- a
  y <- b
  z <- a + b
  return(z)
}
## After the function is invoked, x and y refer to the global scope; the object z defined within the function is no longer accessible.

test.1(1,2)

x

y

z

## The following example shows the access of variables from the local scope (a) and the global scope (x).

x <- 20

test.2 <- function(a) {
  z <- a + x
  return (z)
}

test.2(1)

## Within a function, the <<- operator can be used to change the value in the global scope. If the variable doesn’t exist in the global scope, the <<- operator creates the variable in the global scope.

## In the following example, the function changes the value of x in the global scope and inserts the variable z in the global scope.

x <- 100
y <- 200

test.3 <- function(a, b) {
  x <<- a
  y <- b
  z <<- x + y
  return (z)
}
## After the function returns, the modified values of x and z are available.

test.3(1,2)

x

y

z

# Section #14 - Control Structures

## Some of the control structures provided in R are if-else, for, while, and repeat.

## The following example compares two objects and computes the maximum/minimum of the two. The objects x and y are assumed to be scalars (vectors of unit length).

if (x < y) {
  max <- y
  min <- x
} else {
  max <- x
  min <- y }

## The if-else always returns the last expression from the if part or the else part. The following example shows the assignment of y or x to max based on the outcome of the test.

max <- if (x < y) y else x

## The for loop has the following syntax.
## -> for (name in values) expr

## The following example shows the loop using a vector of values.

x <- c(10, 20, 30)

for (i in x) {
  cat("Square of ", i, " = ", i*i, "\n")
}

## The variable i retains the last value as a side effect.

i

## The loop can be used with any generated sequence of values.

for (i in seq(1,10, by = 2)) {
  cat("Square of ", i, " = ", i*i, "\n")
}

## An example of the while loop for adding the first n numbers is shown below. The loop continues as long as the test is true.

n <- 10
sum <- 0
i <- 1

while (i <= n) {
  sum < sum + i
  i < i+1
}
cat("Sum of first ", n, " numbers = ", sum)

## The break statement may be used to abort the loop. The following example calculates how many numbers add up to the limit and aborts the loop thereafter.

limit <- 55
sum <- 0
i <- 0

while (TRUE) {
  i <- i+1
  sum <- sum + i
  if (sum >= limit) break
}

cat("Sum of first ", i, " numbers = ", sum)

## An example of the repeat statement is shown below. An explicit break is required to come out of the loop.

i <= 1

repeat {
  cat("Square of ", i, " = ", i*i, "\n")
  i <- i+2
  if (i > 10) break
}











