# CS544 Module 6 Assignment
## Student: David J Lotito


#################
# Part1) Strings
#################

library(stringr)

# Use the stringr functions for the following:
# Initialize the vector of words from Lincoln’s speech with the following code:

file <- "http://people.bu.edu/kalathur/datasets/lincoln.txt"
words <- scan(file, what=character())

# a) Detect and show all the words that have a punctuation symbol.

words[str_detect(words, "[:punct:]")]

# b) Replace all the punctuations in the words dataset with an empty string. Remove any resulting empty words from this dataset. Convert all the remaining words to lower case.

remove_punct <- str_replace_all(words, "[:punct:]", "")

(remove_empty_string <- remove_punct[str_detect(remove_punct, '^.+$')])

# Make this the new_words dataset.
new_words <- str_to_lower(remove_empty_string)

# c) What are the top 5 frequent words in the new_words dataset?

names(sort(table(new_words), decreasing = T))[1:5]


# d) Show the frequencies of the word lengths in the new_words dataset. Plot the distribution of these frequencies.

hist(str_length(new_words), xlim = c(1, 15))

# e) What are the words in the new_words dataset with the longest length?

# Find longest length of words
max <- max(str_length(new_words))
# Find longest length words
new_words[str_length(new_words) == max]
# Use regex to find longest length
new_words[str_detect(new_words, "^[a-zA-Z]{16}$")]

# f) Show all the words in the new_words dataset that start with the letter p.

new_words[str_detect(new_words, "^[p]")]

# g) Show all the words in the new_words dataset that end with the letter r.

new_words[str_detect(new_words, "[r]$")]

# h) Show all the words in the new_words dataset that start with the letter p and end with the letter r.

new_words[str_detect(new_words, "^[p]+[a-zA-Z]+[a-zA-Z]+[r]$")]

# In c), you realize that the most spoken words are what are known as stopwords. In text mining, the stopwords are removed before analysis. Initialize the common English stopwords as follows:

stopfile <- "http://people.bu.edu/kalathur/datasets/stopwords.txt" 
stopwords <- scan(stopfile, what=character())

# Remove the stopwords from the new_words data. Use the %in% operator. Repeat c) and d) for this dataset without the stop words.

new_words_WO_stop_words <- new_words[!(new_words %in% stopwords)]

names(sort(table(new_words_WO_stop_words), decreasing = T))[1:5]

hist(str_length(new_words_WO_stop_words), xlim = c(1, 15))

#######################
# Part2) Data Wrangling
#######################

# Use the tidyverse library for the following:

# Download the following csv file, 
# http://people.bu.edu/kalathur/usa_daily_avg_temps.csv
# locally first and use read.csv to load the data into a data frame.

us_daily_temp <- read.csv("/Users/davelotito/Desktop/CS544 - Foundations of Analytics and Data Visualization/Assignments/Assignment_6/usa_daily_avg_temps.csv")

# a) Convert the data frame into a tibble and assign it to the variable usaDailyTemps.

usaDailyTemps <- as_tibble(us_daily_temp)

# b) What are the maximum temperatures recorded for each year? Show the values and also the appropriate plot for the results.
  
(max_temp_year <- usaDailyTemps |> group_by(year) |> summarise(max = max(avgtemp)))

plot <- ggplot(max_temp_year, aes(x = year, y = max))
  
plot + geom_point(alpha = 0.8)

# c) What are the maximum temperatures recorded for each state? Show the values and also the appropriate plot for the results.

(max_temp_state <- usaDailyTemps |> group_by(state) |> summarise(max = max(avgtemp)))

plot <- ggplot(max_temp_state, aes(x = state, y = max))
  
plot + geom_point() + theme(axis.text.x=element_text(angle=90, hjust=1))

# d) Filter the Boston data from usaDailyTemps and assign it to the variable bostonDailyTemps.

bostonDailyTemps <- filter(usaDailyTemps, city == "Boston")

# e) What are the average monthly temperatures for Boston? Show the values and also the appropriate plot for the results. Use the bostonDailyTemps.

(monthly_avg_boston <- bostonDailyTemps |> group_by(month) |> summarise(avg = mean(avgtemp)))

plot <- ggplot(monthly_avg_boston, aes(x = month, y = avg))
  
plot + geom_point() + theme(axis.text.x=element_text(angle=360, hjust=1), axis.line = element_line(colour = "black", 
                      size = 1, linetype = "solid")) + xlim("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
