# Data Analysis Project - CS544
# Student: David Lotito

# Preparing the data
# • Import the data set into R.
# • Document the steps for the import process and any preprocessing had to be done prior to or after the import. Any R code used in the process should be included.

#########################################################################################################
### The dataset is from Kaggle and contains the UFC-Fight historical data from 1993 to 2021. The author scraped the data using beautifulsoup in Python and processed it via Pandas. The file I am using has already be preprocessed and is ready for analysis! ###
#########################################################################################################

# Import CSV
ufc_data <- read.csv("/Users/davelotito/Code/Masters_Degree_Projects/Foundations of Analytics and Data Visualization/Term_Project/UFC_Preprocessed_Fight_Data.csv", header = T)

# Exploritory Analysis

nrow(ufc_data)
ncol(ufc_data)


head(ufc_data, n= 5)

ufc_data[1:3,1:3]

# Analyzing the data
# • Do the analysis as in Module3 for at least one categorical variable and at least one numerical variable. Show appropriate plots for your data.

# Analysis of winner in title bount on color

(winner_title <- ufc_data[(c("Winner", "title_bout"))])

table(winner_title)

barplot(table(winner_title), col = c("Blue", "Red"), xlab = "Title Bout vs. Non-Title Bout", ylab = "Number of Fights", main = "Wins by Color - Title Fight vs. Non-Title Fight")




















